### PR TITLE
Code cleanup. Deleted unnecessary arguments

### PR DESCRIPTION
**Pull request by blasco**

### CODE REVIEW

**Comment by blasco** [comment]
Just some code cleanup, I would also like to add support for the dash delimiters and user delimiters. Working on it

**Comment by Julian** [comment]
Hi, thanks so much.

Definitely would love some help on the delimiter side -- very keen to hear what you have in mind.

On this change specifically though, less sure I see the benefit. The original code here had no conditionals, whereas the new code has quite a few (or really branches). Which in general I think is the reverse direction from what I'd want. Happy to hear thoughts of course.

**Comment by blasco** [comment]
I see your point. For me it was clearer to read like this. Regarding the --, I still didn't find the time. I wish I had it a few times during the week though hahaha so it might worth putting the effort. I'll let you know if I achieve any progress on this.

**Comment by Julian** [comment]
No worries.

Going to close this PR specifically then, but your thoughts or contribution on #7 would be awesome!

**Pull request closed without merging**
